# Generated by Django 3.1 on 2021-02-03 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='createdat',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='updatedat',
            new_name='updated',
        ),
    ]
