# Generated by Django 3.1 on 2021-02-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20210204_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.DateTimeField(null=True),
        ),
    ]
