# Generated by Django 3.1 on 2021-02-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20210204_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
